Add and testing delete bucket script

diff --git a/s3/bash-scripts/delete_bucket b/s3/bash-scripts/delete_bucket
--- a/s3/bash-scripts/delete_bucket
+++ b/s3/bash-scripts/delete_bucket
@@ -1,1 +1,29 @@
 #! /usr/local/bin/bash
+echo "== Deleting S3 bucket =="
+
+# Check for bucket name
+if [ -z "$1" ]; then
+    echo "Error: A bucket name is required. Usage: ./bucket.sh my-bucket-name"
+    exit 1
+fi
+
+BUCKET_NAME=$1
+
+# Check for AWS CLI installation
+if ! command -v aws &> /dev/null; then
+    echo "Error: AWS CLI is not installed. Please install it and try again."
+    exit 1
+fi
+
+
+
+# Delete the S3 bucket
+if [ "$BUCKET_NAME" == $1 ]; then
+    # Create the bucket without location constraint for us-east-1
+    if aws s3api delete-bucket --bucket "$BUCKET_NAME" ; then
+        echo "Bucket '$BUCKET_NAME' deleted successfully."
+    else
+        echo "Error: Failed to delete bucket '$BUCKET_NAME'."
+        exit 1
+    fi
+fi
